image:
  repository: registry1.dso.mil/ironbank/jetstack/cert-manager-controller
  tag: "v1.13.1"

cainjector:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-cainjector
    tag: "v1.13.1"

webhook:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-webhook
    tag: "v1.13.1"

startupapicheck:
  image:
    repository: registry1.dso.mil/ironbank/jetstack/cert-manager-ctl
    tag: "v1.13.1"

  podLabels:
    sidecar.istio.io/inject: "false"

installCRDs: true

# delete secret if certificate is deleted
extraArgs:
  - --enable-certificate-owner-ref=true

securityContext:
  runAsNonRoot: true

prometheus:
  servicemonitor:
    enabled: true
